#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGenerationSqlCommand
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="salon_paris")]
	public partial class DB_CMCADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertCHEVAUX(CHEVAUX instance);
    partial void UpdateCHEVAUX(CHEVAUX instance);
    partial void DeleteCHEVAUX(CHEVAUX instance);
    #endregion
		
		public DB_CMCADataContext() : 
				base(global::WpfGenerationSqlCommand.Properties.Settings.Default.salon_parisConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CMCADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CMCADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CMCADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CMCADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHEVAUX> CHEVAUX
		{
			get
			{
				return this.GetTable<CHEVAUX>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHEVAUX")]
	public partial class CHEVAUX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_CHEVAL;
		
		private string _ID_CATEGORIE;
		
		private char _ID_SERIE;
		
		private string _NOM_CHEVAL;
		
		private string _NATION_CHEVAL;
		
		private string _PERE;
		
		private string _MERE;
		
		private string _ORIGINES;
		
		private string _PROPRIETAIRE;
		
		private System.Nullable<decimal> _TOTAL_QUALIF;
		
		private System.Nullable<decimal> _NOTE_1_QUALIF;
		
		private System.Nullable<decimal> _NOTE_2_QUALIF;
		
		private System.Nullable<decimal> _NOTE_JUGE_QUALIF;
		
		private System.Nullable<decimal> _CALC_QUALIF;
		
		private System.Nullable<int> _RG_QUALIF;
		
		private System.Nullable<int> _RG_QUALIF_OVERALL;
		
		private System.Nullable<int> _RG_OVERALL;
		
		private System.Nullable<decimal> _PTS_FINALE;
		
		private System.Nullable<int> _PARTICIP_FINALE;
		
		private System.Nullable<decimal> _TOTAL_FINAL;
		
		private System.Nullable<int> _ORDRE_QUALIF;
		
		private System.Nullable<int> _ORDRE_FINALE;
		
		private System.Nullable<int> _RG_FINALE;
		
		private System.Nullable<int> _TROPHEE;
		
		private string _ETAON;
		
		private System.Nullable<decimal> _CALC_FINALE;
		
		private System.Nullable<int> _PTS_ELEVEUR;
		
		private string _ELEVEUR;
		
		private System.Nullable<decimal> _NOTE_6;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CHEVALChanging(string value);
    partial void OnID_CHEVALChanged();
    partial void OnID_CATEGORIEChanging(string value);
    partial void OnID_CATEGORIEChanged();
    partial void OnID_SERIEChanging(char value);
    partial void OnID_SERIEChanged();
    partial void OnNOM_CHEVALChanging(string value);
    partial void OnNOM_CHEVALChanged();
    partial void OnNATION_CHEVALChanging(string value);
    partial void OnNATION_CHEVALChanged();
    partial void OnPEREChanging(string value);
    partial void OnPEREChanged();
    partial void OnMEREChanging(string value);
    partial void OnMEREChanged();
    partial void OnORIGINESChanging(string value);
    partial void OnORIGINESChanged();
    partial void OnPROPRIETAIREChanging(string value);
    partial void OnPROPRIETAIREChanged();
    partial void OnTOTAL_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnTOTAL_QUALIFChanged();
    partial void OnNOTE_1_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnNOTE_1_QUALIFChanged();
    partial void OnNOTE_2_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnNOTE_2_QUALIFChanged();
    partial void OnNOTE_JUGE_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnNOTE_JUGE_QUALIFChanged();
    partial void OnCALC_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnCALC_QUALIFChanged();
    partial void OnRG_QUALIFChanging(System.Nullable<int> value);
    partial void OnRG_QUALIFChanged();
    partial void OnRG_QUALIF_OVERALLChanging(System.Nullable<int> value);
    partial void OnRG_QUALIF_OVERALLChanged();
    partial void OnRG_OVERALLChanging(System.Nullable<int> value);
    partial void OnRG_OVERALLChanged();
    partial void OnPTS_FINALEChanging(System.Nullable<decimal> value);
    partial void OnPTS_FINALEChanged();
    partial void OnPARTICIP_FINALEChanging(System.Nullable<int> value);
    partial void OnPARTICIP_FINALEChanged();
    partial void OnTOTAL_FINALChanging(System.Nullable<decimal> value);
    partial void OnTOTAL_FINALChanged();
    partial void OnORDRE_QUALIFChanging(System.Nullable<int> value);
    partial void OnORDRE_QUALIFChanged();
    partial void OnORDRE_FINALEChanging(System.Nullable<int> value);
    partial void OnORDRE_FINALEChanged();
    partial void OnRG_FINALEChanging(System.Nullable<int> value);
    partial void OnRG_FINALEChanged();
    partial void OnTROPHEEChanging(System.Nullable<int> value);
    partial void OnTROPHEEChanged();
    partial void OnETAONChanging(string value);
    partial void OnETAONChanged();
    partial void OnCALC_FINALEChanging(System.Nullable<decimal> value);
    partial void OnCALC_FINALEChanged();
    partial void OnPTS_ELEVEURChanging(System.Nullable<int> value);
    partial void OnPTS_ELEVEURChanged();
    partial void OnELEVEURChanging(string value);
    partial void OnELEVEURChanged();
    partial void OnNOTE_6Changing(System.Nullable<decimal> value);
    partial void OnNOTE_6Changed();
    #endregion
		
		public CHEVAUX()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHEVAL", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_CHEVAL
		{
			get
			{
				return this._ID_CHEVAL;
			}
			set
			{
				if ((this._ID_CHEVAL != value))
				{
					this.OnID_CHEVALChanging(value);
					this.SendPropertyChanging();
					this._ID_CHEVAL = value;
					this.SendPropertyChanged("ID_CHEVAL");
					this.OnID_CHEVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIE", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_CATEGORIE
		{
			get
			{
				return this._ID_CATEGORIE;
			}
			set
			{
				if ((this._ID_CATEGORIE != value))
				{
					this.OnID_CATEGORIEChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORIE = value;
					this.SendPropertyChanged("ID_CATEGORIE");
					this.OnID_CATEGORIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SERIE", DbType="NChar(1) NOT NULL")]
		public char ID_SERIE
		{
			get
			{
				return this._ID_SERIE;
			}
			set
			{
				if ((this._ID_SERIE != value))
				{
					this.OnID_SERIEChanging(value);
					this.SendPropertyChanging();
					this._ID_SERIE = value;
					this.SendPropertyChanged("ID_SERIE");
					this.OnID_SERIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_CHEVAL", DbType="NChar(50)")]
		public string NOM_CHEVAL
		{
			get
			{
				return this._NOM_CHEVAL;
			}
			set
			{
				if ((this._NOM_CHEVAL != value))
				{
					this.OnNOM_CHEVALChanging(value);
					this.SendPropertyChanging();
					this._NOM_CHEVAL = value;
					this.SendPropertyChanged("NOM_CHEVAL");
					this.OnNOM_CHEVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATION_CHEVAL", DbType="NChar(3)")]
		public string NATION_CHEVAL
		{
			get
			{
				return this._NATION_CHEVAL;
			}
			set
			{
				if ((this._NATION_CHEVAL != value))
				{
					this.OnNATION_CHEVALChanging(value);
					this.SendPropertyChanging();
					this._NATION_CHEVAL = value;
					this.SendPropertyChanged("NATION_CHEVAL");
					this.OnNATION_CHEVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERE", DbType="NChar(255)")]
		public string PERE
		{
			get
			{
				return this._PERE;
			}
			set
			{
				if ((this._PERE != value))
				{
					this.OnPEREChanging(value);
					this.SendPropertyChanging();
					this._PERE = value;
					this.SendPropertyChanged("PERE");
					this.OnPEREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MERE", DbType="NChar(500)")]
		public string MERE
		{
			get
			{
				return this._MERE;
			}
			set
			{
				if ((this._MERE != value))
				{
					this.OnMEREChanging(value);
					this.SendPropertyChanging();
					this._MERE = value;
					this.SendPropertyChanged("MERE");
					this.OnMEREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGINES", DbType="NChar(500)")]
		public string ORIGINES
		{
			get
			{
				return this._ORIGINES;
			}
			set
			{
				if ((this._ORIGINES != value))
				{
					this.OnORIGINESChanging(value);
					this.SendPropertyChanging();
					this._ORIGINES = value;
					this.SendPropertyChanged("ORIGINES");
					this.OnORIGINESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPRIETAIRE", DbType="NChar(255)")]
		public string PROPRIETAIRE
		{
			get
			{
				return this._PROPRIETAIRE;
			}
			set
			{
				if ((this._PROPRIETAIRE != value))
				{
					this.OnPROPRIETAIREChanging(value);
					this.SendPropertyChanging();
					this._PROPRIETAIRE = value;
					this.SendPropertyChanged("PROPRIETAIRE");
					this.OnPROPRIETAIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_QUALIF", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TOTAL_QUALIF
		{
			get
			{
				return this._TOTAL_QUALIF;
			}
			set
			{
				if ((this._TOTAL_QUALIF != value))
				{
					this.OnTOTAL_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_QUALIF = value;
					this.SendPropertyChanged("TOTAL_QUALIF");
					this.OnTOTAL_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE_1_QUALIF", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> NOTE_1_QUALIF
		{
			get
			{
				return this._NOTE_1_QUALIF;
			}
			set
			{
				if ((this._NOTE_1_QUALIF != value))
				{
					this.OnNOTE_1_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._NOTE_1_QUALIF = value;
					this.SendPropertyChanged("NOTE_1_QUALIF");
					this.OnNOTE_1_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE_2_QUALIF", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> NOTE_2_QUALIF
		{
			get
			{
				return this._NOTE_2_QUALIF;
			}
			set
			{
				if ((this._NOTE_2_QUALIF != value))
				{
					this.OnNOTE_2_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._NOTE_2_QUALIF = value;
					this.SendPropertyChanged("NOTE_2_QUALIF");
					this.OnNOTE_2_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE_JUGE_QUALIF", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> NOTE_JUGE_QUALIF
		{
			get
			{
				return this._NOTE_JUGE_QUALIF;
			}
			set
			{
				if ((this._NOTE_JUGE_QUALIF != value))
				{
					this.OnNOTE_JUGE_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._NOTE_JUGE_QUALIF = value;
					this.SendPropertyChanged("NOTE_JUGE_QUALIF");
					this.OnNOTE_JUGE_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALC_QUALIF", AutoSync=AutoSync.Always, DbType="Decimal(34,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> CALC_QUALIF
		{
			get
			{
				return this._CALC_QUALIF;
			}
			set
			{
				if ((this._CALC_QUALIF != value))
				{
					this.OnCALC_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._CALC_QUALIF = value;
					this.SendPropertyChanged("CALC_QUALIF");
					this.OnCALC_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG_QUALIF", DbType="Int")]
		public System.Nullable<int> RG_QUALIF
		{
			get
			{
				return this._RG_QUALIF;
			}
			set
			{
				if ((this._RG_QUALIF != value))
				{
					this.OnRG_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._RG_QUALIF = value;
					this.SendPropertyChanged("RG_QUALIF");
					this.OnRG_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG_QUALIF_OVERALL", DbType="Int")]
		public System.Nullable<int> RG_QUALIF_OVERALL
		{
			get
			{
				return this._RG_QUALIF_OVERALL;
			}
			set
			{
				if ((this._RG_QUALIF_OVERALL != value))
				{
					this.OnRG_QUALIF_OVERALLChanging(value);
					this.SendPropertyChanging();
					this._RG_QUALIF_OVERALL = value;
					this.SendPropertyChanged("RG_QUALIF_OVERALL");
					this.OnRG_QUALIF_OVERALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG_OVERALL", DbType="Int")]
		public System.Nullable<int> RG_OVERALL
		{
			get
			{
				return this._RG_OVERALL;
			}
			set
			{
				if ((this._RG_OVERALL != value))
				{
					this.OnRG_OVERALLChanging(value);
					this.SendPropertyChanging();
					this._RG_OVERALL = value;
					this.SendPropertyChanged("RG_OVERALL");
					this.OnRG_OVERALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTS_FINALE", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> PTS_FINALE
		{
			get
			{
				return this._PTS_FINALE;
			}
			set
			{
				if ((this._PTS_FINALE != value))
				{
					this.OnPTS_FINALEChanging(value);
					this.SendPropertyChanging();
					this._PTS_FINALE = value;
					this.SendPropertyChanged("PTS_FINALE");
					this.OnPTS_FINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTICIP_FINALE", DbType="Int")]
		public System.Nullable<int> PARTICIP_FINALE
		{
			get
			{
				return this._PARTICIP_FINALE;
			}
			set
			{
				if ((this._PARTICIP_FINALE != value))
				{
					this.OnPARTICIP_FINALEChanging(value);
					this.SendPropertyChanging();
					this._PARTICIP_FINALE = value;
					this.SendPropertyChanged("PARTICIP_FINALE");
					this.OnPARTICIP_FINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_FINAL", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TOTAL_FINAL
		{
			get
			{
				return this._TOTAL_FINAL;
			}
			set
			{
				if ((this._TOTAL_FINAL != value))
				{
					this.OnTOTAL_FINALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_FINAL = value;
					this.SendPropertyChanged("TOTAL_FINAL");
					this.OnTOTAL_FINALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDRE_QUALIF", DbType="Int")]
		public System.Nullable<int> ORDRE_QUALIF
		{
			get
			{
				return this._ORDRE_QUALIF;
			}
			set
			{
				if ((this._ORDRE_QUALIF != value))
				{
					this.OnORDRE_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._ORDRE_QUALIF = value;
					this.SendPropertyChanged("ORDRE_QUALIF");
					this.OnORDRE_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDRE_FINALE", DbType="Int")]
		public System.Nullable<int> ORDRE_FINALE
		{
			get
			{
				return this._ORDRE_FINALE;
			}
			set
			{
				if ((this._ORDRE_FINALE != value))
				{
					this.OnORDRE_FINALEChanging(value);
					this.SendPropertyChanging();
					this._ORDRE_FINALE = value;
					this.SendPropertyChanged("ORDRE_FINALE");
					this.OnORDRE_FINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG_FINALE", DbType="Int")]
		public System.Nullable<int> RG_FINALE
		{
			get
			{
				return this._RG_FINALE;
			}
			set
			{
				if ((this._RG_FINALE != value))
				{
					this.OnRG_FINALEChanging(value);
					this.SendPropertyChanging();
					this._RG_FINALE = value;
					this.SendPropertyChanged("RG_FINALE");
					this.OnRG_FINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TROPHEE", DbType="Int")]
		public System.Nullable<int> TROPHEE
		{
			get
			{
				return this._TROPHEE;
			}
			set
			{
				if ((this._TROPHEE != value))
				{
					this.OnTROPHEEChanging(value);
					this.SendPropertyChanging();
					this._TROPHEE = value;
					this.SendPropertyChanged("TROPHEE");
					this.OnTROPHEEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETAON", DbType="NChar(500)")]
		public string ETAON
		{
			get
			{
				return this._ETAON;
			}
			set
			{
				if ((this._ETAON != value))
				{
					this.OnETAONChanging(value);
					this.SendPropertyChanging();
					this._ETAON = value;
					this.SendPropertyChanged("ETAON");
					this.OnETAONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALC_FINALE", AutoSync=AutoSync.Always, DbType="Decimal(33,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> CALC_FINALE
		{
			get
			{
				return this._CALC_FINALE;
			}
			set
			{
				if ((this._CALC_FINALE != value))
				{
					this.OnCALC_FINALEChanging(value);
					this.SendPropertyChanging();
					this._CALC_FINALE = value;
					this.SendPropertyChanged("CALC_FINALE");
					this.OnCALC_FINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTS_ELEVEUR", DbType="Int")]
		public System.Nullable<int> PTS_ELEVEUR
		{
			get
			{
				return this._PTS_ELEVEUR;
			}
			set
			{
				if ((this._PTS_ELEVEUR != value))
				{
					this.OnPTS_ELEVEURChanging(value);
					this.SendPropertyChanging();
					this._PTS_ELEVEUR = value;
					this.SendPropertyChanged("PTS_ELEVEUR");
					this.OnPTS_ELEVEURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELEVEUR", DbType="NChar(100)")]
		public string ELEVEUR
		{
			get
			{
				return this._ELEVEUR;
			}
			set
			{
				if ((this._ELEVEUR != value))
				{
					this.OnELEVEURChanging(value);
					this.SendPropertyChanging();
					this._ELEVEUR = value;
					this.SendPropertyChanged("ELEVEUR");
					this.OnELEVEURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE_6", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> NOTE_6
		{
			get
			{
				return this._NOTE_6;
			}
			set
			{
				if ((this._NOTE_6 != value))
				{
					this.OnNOTE_6Changing(value);
					this.SendPropertyChanging();
					this._NOTE_6 = value;
					this.SendPropertyChanged("NOTE_6");
					this.OnNOTE_6Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
